### ISSUE TITLE
Main Roadmap

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/hello-vue#1]
According to book chapters:
- [ ] template syntax (1)
- [ ] components (2)
- [ ] routing (3)
- [ ] handling user interaction (4)
- [ ] binding from inputs (5)
- [ ] manage state with vueX (6)
- [ ] plugins (7)
- [ ] testing (8)
